### ISSUE TITLE
error in main.nf - incorrect param

### ISSUE THREAD

**Issue by sjlow23** [esteinig/cerebro#39]
This should be `50` not `50c` 
https://github.com/esteinig/cerebro/blob/8a66f362362f6877f60cd5c30dac82607f9cff0d/main.nf#L151

causes this error:

```
ERROR ~ No such variable: c
```

**Comment by esteinig** [comment]
Hey sorry Soo Jen, the pipeline on `main` should not be used currently! It's under development, and probably won't work at all right now (ONT integration half-way done) - but thanks for this, correcting it now.

**Comment by ammaraziz** [comment]
Thanks Eike. That was actually me submitting the bug. Let me know if you don't want these fixes.

We're going to run an older commit and stay out of your way :)

**Comment by esteinig** [comment]
Soo Jen told me - sorry for the trouble! You can see there is a species identification and the ONT workflow for the Alfred in the works - it's a mess on main though, will revisit next week and bring this into a sharable format since Jean is also pushing on the wet-lab protocol and transfer :)
